### PR TITLE
Fix All flake8 Errors and Add a dedicated flake8 Github Action

### PR DESCRIPTION
**Pull request by luoos**
Fix flake8 errors and add a dedicated flake8 Github action. Also, add a flake8 badge to README.

Two errors are ignored:

- C901: Function is too complex (too much branching logic). This PR is meant to fix the style issues.
- W503: line break before binary operator. It's not compatible with PEP8.

Original flake8 errors:

```
$ flake8 . --count --ignore=C901,W503 --max-complexity=10 --max-line-length=127 --statistics
./setup.py:28:20: E231 missing whitespace after ':'
./setup.py:39:20: E251 unexpected spaces around keyword / parameter equals
./setup.py:39:22: E251 unexpected spaces around keyword / parameter equals
./example/generate_examples.py:13:45: E225 missing whitespace around operator
./example/generate_examples.py:18:35: W291 trailing whitespace
./example/generate_examples.py:26:39: W292 no newline at end of file
./example/src/different_sorts.py:77:1: E302 expected 2 blank lines, found 1
./example/src/different_sorts.py:126:20: W292 no newline at end of file
./example/src/gradient_descent.py:120:34: E226 missing whitespace around arithmetic operator
./example/src/logging_integration.py:10:17: E226 missing whitespace around arithmetic operator
./example/src/logging_integration.py:10:28: E226 missing whitespace around arithmetic operator
./example/src/logging_integration.py:17:7: W292 no newline at end of file
./example/src/function_args_return.py:8:17: E226 missing whitespace around arithmetic operator
./example/src/function_args_return.py:8:28: E226 missing whitespace around arithmetic operator
./example/src/function_args_return.py:11:35: W291 trailing whitespace
./example/src/function_args_return.py:12:37: W291 trailing whitespace
./example/src/multithread.py:11:17: E226 missing whitespace around arithmetic operator
./example/src/multithread.py:11:28: E226 missing whitespace around arithmetic operator
./example/src/multithread.py:25:1: W293 blank line contains whitespace
./example/src/multithread.py:30:1: W293 blank line contains whitespace
./example/src/multithread.py:32:1: W293 blank line contains whitespace
./example/src/mcts_game.py:80:48: W292 no newline at end of file
./tests/test_multiprocess.py:12:1: E122 continuation line missing indentation or outdented
./tests/test_multiprocess.py:19:1: E122 continuation line missing indentation or outdented
./tests/test_multiprocess.py:28:1: E122 continuation line missing indentation or outdented
./tests/test_multiprocess.py:42:1: E122 continuation line missing indentation or outdented
./tests/test_multiprocess.py:65:1: E122 continuation line missing indentation or outdented
./tests/test_multiprocess.py:93:1: E122 continuation line missing indentation or outdented
./tests/test_multiprocess.py:134:128: E501 line too long (175 > 127 characters)
./tests/test_multiprocess.py:145:128: E501 line too long (179 > 127 characters)
./tests/test_multiprocess.py:155:128: E501 line too long (221 > 127 characters)
./tests/test_multiprocess.py:159:128: E501 line too long (214 > 127 characters)
./tests/test_multiprocess.py:161:128: E501 line too long (173 > 127 characters)
./tests/test_multiprocess.py:168:128: E501 line too long (233 > 127 characters)
./tests/cmdline_tmpl.py:12:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:12:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:19:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:27:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:34:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:42:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:50:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:79:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:100:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:120:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:129:1: E122 continuation line missing indentation or outdented
./tests/test_cmdline.py:154:128: E501 line too long (128 > 127 characters)
./tests/test_cmdline.py:155:128: E501 line too long (134 > 127 characters)
./tests/test_cmdline.py:157:128: E501 line too long (139 > 127 characters)
./tests/test_cmdline.py:158:128: E501 line too long (145 > 127 characters)
./tests/test_cmdline.py:174:128: E501 line too long (136 > 127 characters)
./tests/test_cmdline.py:176:128: E501 line too long (183 > 127 characters)
./tests/test_cmdline.py:177:128: E501 line too long (180 > 127 characters)
./tests/test_cmdline.py:182:128: E501 line too long (136 > 127 characters)
./tests/test_cmdline.py:184:128: E501 line too long (173 > 127 characters)
./tests/test_cmdline.py:201:128: E501 line too long (156 > 127 characters)
./tests/test_cmdline.py:206:17: E128 continuation line under-indented for visual indent
./tests/test_cmdline.py:207:128: E501 line too long (140 > 127 characters)
./tests/test_cmdline.py:208:17: E128 continuation line under-indented for visual indent
./tests/test_cmdline.py:215:128: E501 line too long (156 > 127 characters)
./tests/test_cmdline.py:223:128: E501 line too long (150 > 127 characters)
./tests/test_cmdline.py:224:128: E501 line too long (182 > 127 characters)
./tests/test_cmdline.py:236:128: E501 line too long (176 > 127 characters)
./tests/test_cmdline.py:237:128: E501 line too long (174 > 127 characters)
./tests/test_cmdline.py:238:128: E501 line too long (180 > 127 characters)
./tests/test_cmdline.py:241:128: E501 line too long (175 > 127 characters)
./tests/test_cmdline.py:249:128: E501 line too long (188 > 127 characters)
./tests/test_cmdline.py:252:128: E501 line too long (186 > 127 characters)
./tests/test_cmdline.py:255:128: E501 line too long (178 > 127 characters)
./tests/test_cmdline.py:257:128: E501 line too long (177 > 127 characters)
./tests/test_cmdline.py:263:128: E501 line too long (164 > 127 characters)
./tests/test_cmdline.py:276:128: E501 line too long (162 > 127 characters)
./tests/test_performance.py:77:128: E501 line too long (174 > 127 characters)
./tests/test_performance.py:78:128: E501 line too long (150 > 127 characters)
./tests/test_logsparse.py:11:1: E122 continuation line missing indentation or outdented
./tests/test_logsparse.py:26:1: E122 continuation line missing indentation or outdented
./tests/test_logsparse.py:61:128: E501 line too long (167 > 127 characters)
./tests/test_logsparse.py:62:128: E501 line too long (154 > 127 characters)
./tests/test_logsparse.py:72:128: E501 line too long (228 > 127 characters)
./tests/test_prog_snapshot.py:9:128: E501 line too long (1405 > 127 characters)
./tests/test_prog_snapshot.py:76:128: E501 line too long (210 > 127 characters)
./tests/test_prog_snapshot.py:80:128: E501 line too long (319 > 127 characters)
./tests/test_prog_snapshot.py:94:128: E501 line too long (318 > 127 characters)
./tests/test_prog_snapshot.py:102:128: E501 line too long (375 > 127 characters)
./tests/test_regression.py:94:1: E122 continuation line missing indentation or outdented
./tests/test_regression.py:111:128: E501 line too long (128 > 127 characters)
./tests/test_regression.py:121:1: E122 continuation line missing indentation or outdented
./tests/test_regression.py:164:1: E122 continuation line missing indentation or outdented
./tests/test_regression.py:183:128: E501 line too long (153 > 127 characters)
./tests/test_regression.py:189:128: E501 line too long (129 > 127 characters)
./tests/data/vdb_multithread.py:10:16: E226 missing whitespace around arithmetic operator
./tests/data/vdb_multithread.py:10:26: E226 missing whitespace around arithmetic operator
./tests/data/vdb_multithread.py:17:17: E226 missing whitespace around arithmetic operator
./tests/data/vdb_multithread.py:17:28: E226 missing whitespace around arithmetic operator
./tests/data/vdb_basic.py:1:1: E265 block comment should start with '# '
./tests/data/vdb_basic.py:2:1: F401 'time' imported but unused
./tests/data/vdb_basic.py:4:1: E265 block comment should start with '# '
./tests/data/vdb_basic.py:10:13: E226 missing whitespace around arithmetic operator
./tests/data/vdb_basic.py:10:16: E226 missing whitespace around arithmetic operator
./tests/data/vdb_basic.py:12:1: E302 expected 2 blank lines, found 1
./tests/data/vdb_basic.py:15:5: E265 block comment should start with '# '
./tests/data/vdb_basic.py:17:1: E302 expected 2 blank lines, found 1
./tests/data/vdb_basic.py:18:5: E265 block comment should start with '# '
./tests/data/vdb_basic.py:19:10: E226 missing whitespace around arithmetic operator
./tests/data/vdb_basic.py:21:8: E226 missing whitespace around arithmetic operator
./tests/data/vdb_basic.py:21:13: E226 missing whitespace around arithmetic operator
./tests/data/vdb_basic.py:22:5: E265 block comment should start with '# '
./tests/data/vdb_basic.py:25:1: E302 expected 2 blank lines, found 1
./tests/data/vdb_basic.py:26:8: E226 missing whitespace around arithmetic operator
./tests/data/vdb_basic.py:26:13: E226 missing whitespace around arithmetic operator
./tests/data/vdb_basic.py:28:8: E226 missing whitespace around arithmetic operator
./tests/data/vdb_basic.py:30:1: E305 expected 2 blank lines after class or function definition, found 1
./tests/data/vdb_basic.py:36:30: W292 no newline at end of file
./tests/data/fib.py:4:17: E226 missing whitespace around arithmetic operator
./tests/data/fib.py:4:28: E226 missing whitespace around arithmetic operator
./docs/source/conf.py:1:1: F401 'sphinx_rtd_theme' imported but unused
./docs/source/conf.py:65:31: W292 no newline at end of file
./src/viztracer/report_builder.py:63:21: E127 continuation line over-indented for visual indent
./src/viztracer/report_builder.py:67:128: E501 line too long (144 > 127 characters)
./src/viztracer/viztracer.py:36:17: E126 continuation line over-indented for hanging indent
./src/viztracer/functree.py:46:17: E126 continuation line over-indented for hanging indent
./src/viztracer/main.py:51:128: E501 line too long (135 > 127 characters)
./src/viztracer/main.py:53:128: E501 line too long (140 > 127 characters)
./src/viztracer/main.py:89:128: E501 line too long (162 > 127 characters)
./src/viztracer/main.py:97:128: E501 line too long (129 > 127 characters)
./src/viztracer/main.py:137:128: E501 line too long (145 > 127 characters)
./src/viztracer/main.py:354:128: E501 line too long (138 > 127 characters)
./src/viztracer/tracer.py:296:128: E501 line too long (133 > 127 characters)
./src/viztracer/tracer.py:297:128: E501 line too long (161 > 127 characters)
./src/viztracer/code_monkey.py:160:21: E126 continuation line over-indented for hanging indent
./src/viztracer/code_monkey.py:166:21: E126 continuation line over-indented for hanging indent
./src/viztracer/code_monkey.py:172:21: E126 continuation line over-indented for hanging indent
./src/viztracer/code_monkey.py:181:17: E126 continuation line over-indented for hanging indent
22    E122 continuation line missing indentation or outdented
6     E126 continuation line over-indented for hanging indent
1     E127 continuation line over-indented for visual indent
2     E128 continuation line under-indented for visual indent
1     E225 missing whitespace around operator
21    E226 missing whitespace around arithmetic operator
1     E231 missing whitespace after ':'
2     E251 unexpected spaces around keyword / parameter equals
5     E265 block comment should start with '# '
4     E302 expected 2 blank lines, found 1
1     E305 expected 2 blank lines after class or function definition, found 1
52    E501 line too long (135 > 127 characters)
2     F401 'sphinx_rtd_theme' imported but unused
3     W291 trailing whitespace
6     W292 no newline at end of file
3     W293 blank line contains whitespace
132
```

### CODE REVIEW

**Comment by luoos** [comment]
There is a failed test. But it seems a flaky test because the same test passed on my forked repo. Please refer to [build #4](https://github.com/luoos/viztracer/actions/runs/428978070).

**Comment by gaogaotiantian** [comment]
Are you doing this manually or using some auto tools? Could you change the Makefile as well? There's some flake8 related command in the Makefile.

**Comment by luoos** [comment]
> Are you doing this manually or using some auto tools? Could you change the Makefile as well? There's some flake8 related command in the Makefile.

Manually. Is there any such auto tool? That would be great.
OK. I will take a look at the Makefile.

**Comment by luoos** [comment]
> > Are you doing this manually or using some auto tools? Could you change the Makefile as well? There's some flake8 related command in the Makefile.
> 
> Manually. Is there any such auto tool? That would be great.
> OK. I will take a look at the Makefile.

Done. Add a new [commit](https://github.com/gaogaotiantian/viztracer/pull/70/commits/f84fa6728941ae9eb22b92a352d00dbfd7b06cce). Just copy those two commands from the YAML files.

**Comment by luoos** [comment]
I noticed that there are two flake8 commands in [python-package.yml](https://github.com/gaogaotiantian/viztracer/blob/5fc4e23104f5cd6c0d05c26ccf905d2c2b794fba/.github/workflows/python-package.yml#L45). Should I delete it directly?

**Comment by luoos** [comment]
> I noticed that there are two flake8 commands in [python-package.yml](https://github.com/gaogaotiantian/viztracer/blob/5fc4e23104f5cd6c0d05c26ccf905d2c2b794fba/.github/workflows/python-package.yml#L45). Should I delete them directly?

Add a commit to remove flake8 from python-package.yml. If it's not necessary, I will delete this commit.

**Comment by gaogaotiantian** [comment]
The reason it had two flake8 checks was because the second one is "warning". Now that we can enforce flake8, we do not need two checks anymore. You can remove the first one, and use the one you added in the new flake8 yml file in Makefile. 

Also, if C901 is ignored, ```--max-complexity``` is useless right? Could you remove it?

So basically we should only have a single flake8 check in two places

* the flake8 yml for github action
* Makefile

This is not an easy job, I really appreciate your contribution. I considered enforcing some lint rules but was too lazy to make everything work. Thanks!

**Comment by luoos** [comment]
Aha, I was trying to ask if two flake8 commands are necessary. Now I can remove the first safely.

For C901, my initial guess is that `--max-complexity` can check various kinds of errors, not just C901. But I searched a little bit. It seems that `--max-complexity` is only for C901. So we can remove both C901 and `--max-complexity`.

**Comment by luoos** [comment]
> The reason it had two flake8 checks was because the second one is "warning". Now that we can enforce flake8, we do not need two checks anymore. You can remove the first one, and use the one you added in the new flake8 yml file in Makefile.
> 
> Also, if C901 is ignored, `--max-complexity` is useless right? Could you remove it?
> 
> So basically we should only have a single flake8 check in two places
> 
> * the flake8 yml for github action
> * Makefile
> 
> This is not an easy job, I really appreciate your contribution. I considered enforcing some lint rules but was too lazy to make everything work. Thanks!

Done.

This project looks promising! Hope I can contribute more!

**Comment by gaogaotiantian** [comment]
Thank you for the effort, contributions are super welcome for the project. If it's a relatively large change or new feature, please discuss it first through issues or the brand new github discussions :)

**Pull request merged**
