### PR TITLE
Fix test viewer

### PR DESCRIPTION
**Pull request by acehinnnqru**
This is a pull request to solve issue #269.
Summary:
- Add _find_a_free_port into TestViewer
- Add URL method to Viewer
- Change cases use 9001 port to a free dynamic port found before creating a viewer.

### CODE REVIEW

**Comment by acehinnnqru** [comment]
Hmmm, there may be a problem that where should the _find_a_free_port method put.

In previous commits, I tried to put it in Viewer but I changed it.

**Comment by acehinnnqru** [comment]
Oh, there may exist a problem in mac M1 Max that the `test_use_external_processor` can not pass( I did not change any code or logic).

**Comment by gaogaotiantian** [comment]
Also, it would be great if you run lint first :)

**Comment by acehinnnqru** [comment]
Sorry, I forgot to lint again when I fix an error.

**Comment by gaogaotiantian** [comment]
Interesting. It failed the exact test that I wanted to patch. Forcing me to think about it again actually gives me a new idea.

It's always the same test that failed - `test_once_timeout`. Now I believe the reason was the viewer process could exit(so close the socket) before the test can test on it, because the `--timeout` argument, which will result in a failure. In this case, as we do want to test the timeout feature for the viewer, we should increase the timeout of `test_once_timeout` to make sure it won't exit before the test confirm the status of the socket. Increasing it to 4/5 should do it.

As for the other changes, I think the `url()` piece is good. We should add a new test to test whether viewer could work on a random port, using your new `_find_a_free_port()` method. However, for all the other tests, let's just test on 9001, which is the most common use case for the users.

**Comment by acehinnnqru** [comment]
Yeah, you're right. I did not meet the error after I use `_find_a_free_port` which is weird.

When I saw these cases, I found that the URL or port was hardcoded which is not so good to change when the port or host changed. So, I add a `url` method.

**Comment by acehinnnqru** [comment]
But why I can pass in my own mac?

**Comment by gaogaotiantian** [comment]
It's a racing issue, so the test will *occasionally* fail. If it always fails, I won't check it in to begin with. So, it's normal that it can pass in your local machine.

So, could you change the test fixes where you used `_find_a_free_port()` and add a new test using that just to test a random port? If you want, you can increase the timeout for `test_once_timeout` too.

**Comment by acehinnnqru** [comment]
OK, I will push the changes tonight.

**Review by gaogaotiantian — CHANGES_REQUESTED** [review]

**Comment by Fred-Black** [comment]
At first, I cannot pass test_use_external_processor too, it seems still runs on port9001(I changed 10000 to 9001 and passed).  After I see this request, I tried new code and passed the test, but it seems uses too many ports? for reference:
image

**Comment by acehinnnqru** [comment]
I have completed the changes. You can check them.

**Comment by gaogaotiantian** [comment]
I believe next time you can use "request for review" feature when you finish your changes.

**Comment by acehinnnqru** [comment]
> I believe next time you can use "request for review" feature when you finish your changes.

Sorry, I am new to make PR to a project.

**Pull request merged**
