### PR TITLE
Add instant event compresss/decompress

### PR DESCRIPTION
**Pull request by LorewalkerZhou**
Test result：
- OS:  macOS Monterey 12.3.1
- make lint
> Success: no issues found in 24 source files
- make test
> Failed case: test_sanitize_function_name, test_use_external_processor
> Blocked case: test_attach

But I don`t think my modification will affect the above functions.

### CODE REVIEW

**Comment by TTianshun** [comment]
It seems PyObject_JsonDumps has a memory leak issue
since `PyUnicode_AsUTF8(ret)` returns the address of string in PyUnicodeObject, `Py_DECREF(ret)` will release the memory

**Comment by LorewalkerZhou** [comment]
> since `PyUnicode_AsUTF8(ret)` returns the address of string in PyUnicodeObject

My commit can compress and decompress event instant correctly. I have some doubts about the correctness of this statement. I didn't see a similar description in the python documentation. Could you tell me the source of this statement?

**Comment by gaogaotiantian** [comment]
Hi, sorry it took so long to take a look at your PR. The reason was because #278 was also working on compression features and having two PRs probably makes it more difficult.

As the other PR is merged, we can take a look at this now. Overall the code quality is good. However, you probably need to rebase on the current `trace-log-compressor` branch and fix the conflict.

An important change was that now `json` library is imported and globally available. It could probably make your life easier to dump json strings. You can refer to the existing code.

If you are still willing to work on this, after you rebase and update your PR, I'll do a code review.

**Comment by LorewalkerZhou** [comment]
It is not my intention to close this PR. I will submit a new PR later.

**Pull request closed without merging**
