### PR TITLE
Compress fee args

### PR DESCRIPTION
**Pull request by TTianshun**
Add compressor for fee args, which will happen when enable `log_func_args` and `log_func_retval`

### CODE REVIEW

**Comment by gaogaotiantian** [comment]
If we put the argument exist flag after the timestamps, we can get rid of the offset right? And the logic would be simpler.

**Comment by TTianshun** [comment]
> If we put the argument exist flag after the timestamps, we can get rid of the offset right? And the logic would be simpler.

I write like this because I want to iterate the list only once while reading and writing. if we put the argument exist flag after the timestamp. We have to iterate the fee events again. considering fee is the major of trace file, the time cost might be more.

**Comment by gaogaotiantian** [comment]
There's a more critical issue - you assumed that all the FEEs of the same function will either have `args` or not. That's not always the case. It's possible that some of the FEEs have `args` and the others don't. We need to take care of that.

**Comment by TTianshun** [comment]
> There's a more critical issue - you assumed that all the FEEs of the same function will either have `args` or not. That's not always the case. It's possible that some of the FEEs have `args` and the others don't. We need to take care of that.

That should be considered in `parse_trace_events` function. For the same function events with or without args, they are seperately stored and wrote. The test case should also include it.

**Comment by gaogaotiantian** [comment]
> > There's a more critical issue - you assumed that all the FEEs of the same function will either have `args` or not. That's not always the case. It's possible that some of the FEEs have `args` and the others don't. We need to take care of that.
> 
> That should be considered in `parse_trace_events` function. For the same function events with or without args, they are seperately stored and wrote. The test case should also include it.

Ah, right, you kept them into different keys.

**Comment by gaogaotiantian** [comment]
Then let's get rid of the flag piece. Only have the offset - if the offset is `0` then it means no args. It's impossible for the offset to be `0` as long as there are entries. The logic would still be simpler.

For writing it's actually fine - you are assembling a list then write to the file anyway. For reading yeah it's probably easier to have both the timestamp and arg list ready to generate events.

**Comment by TTianshun** [comment]
Could you review these changes? @gaogaotiantian

**Pull request merged**
